Unit Test Method 작성
depromeet/bread-map-backend pull request #88
Opened 2021-11-01 12:37 UTC by earth-h

Unit Test Method 작성 중
* 완료 아닙니다!

2021-11-06 15:29 UTC, Jane096 approved these changes

2021-11-11 15:35 UTC, Jane096 requested changes

2021-11-11 15:35 UTC, Jane096 commented on src/test/java/com/depromeet/breadmapbackend/earth/MenuReviewsServiceTest.java
> +//
이거 if(menu == null ) 조건으로 걸어야 테스트 돌릴 때 else 구문으로 타지 않을 것 같아요!

2021-11-11 15:35 UTC, Jane096 commented on src/test/java/com/depromeet/breadmapbackend/earth/MenuReviewsServiceTest.java
> +//
그리고 menu.createMenu() bakery 넘겨주는 부분에서, 양방향 관계로 menuReviewList add 시켜줄 때 해당 값이 현재 넘어가지 않아 NPE 날 수 있을 것 같습니다

2021-11-11 15:35 UTC, Jane096 commented on src/test/java/com/depromeet/breadmapbackend/earth/MenuReviewsServiceTest.java
> +//
findByBreadCategoryName(any(String.class).replaceAll("[ /]", ""))).thenReturn(breadCategories)

이 부분에서도 위에 BreadCategories 셋팅 값에 과자류로 해두셔서 any(String.class) 라고 한다면 argument mismatch가 뜰 수 있습니다. 아무 String 값이 아니라 "과자류" 라고 해야 할 것 같아요

2021-11-12 06:47 UTC, earth-h commented on src/test/java/com/depromeet/breadmapbackend/earth/MenuReviewsServiceTest.java
> +//
서비스를 아예 호출 안했더라구요.. 허헣

2021-11-12 07:17 UTC, Jane096 commented on src/test/java/com/depromeet/breadmapbackend/earth/MenuReviewsServiceTest.java
> +//
아핫..! 맞아요 서비스 then() 전에 호출해줘야할거같네요 :)

2021-11-12 07:23 UTC, Jane096 approved these changes

2021-11-13 02:28 UTC, Jane096 approved these changes

2021-11-13 02:48 UTC, merged